export const WORKSPACE_TEMPLATES = [
  {
    id: "development",
    name: "Development",
    description: "Code repositories, CI/CD pipelines, and engineering docs in one sandbox.",
    icon: "💻",
    category: "Development",
    color: "from-blue-500/20 to-indigo-500/10",
    accentColor: "#4F8CFF",
    tags: ["code", "engineering"],
  },
  {
    id: "research",
    name: "Research Lab",
    description: "Collect papers, experiments, and findings with structured knowledge layers.",
    icon: "🔬",
    category: "Research",
    color: "from-purple-500/20 to-pink-500/10",
    accentColor: "#A855F7",
    tags: ["research", "papers"],
  },
  {
    id: "startup",
    name: "Startup HQ",
    description: "Pitch decks, investor updates, and product roadmaps for your venture.",
    icon: "🚀",
    category: "Startup",
    color: "from-orange-500/20 to-amber-500/10",
    accentColor: "#F97316",
    tags: ["startup", "business"],
  },
  {
    id: "ai-project",
    name: "AI Project",
    description: "Model experiments, prompt libraries, and AI session histories.",
    icon: "🤖",
    category: "AI Project",
    color: "from-cyan-500/20 to-blue-500/10",
    accentColor: "#06B6D4",
    tags: ["ai", "ml"],
  },
  {
    id: "college",
    name: "College Studies",
    description: "Lecture notes, assignments, and semester planning in one place.",
    icon: "🎓",
    category: "College",
    color: "from-emerald-500/20 to-teal-500/10",
    accentColor: "#10B981",
    tags: ["education", "college"],
  },
  {
    id: "freelancing",
    name: "Freelance Studio",
    description: "Client deliverables, contracts, and project timelines organized.",
    icon: "💼",
    category: "Freelancing",
    color: "from-rose-500/20 to-red-500/10",
    accentColor: "#F43F5E",
    tags: ["freelance", "clients"],
  },
  {
    id: "personal",
    name: "Personal Space",
    description: "Private notes, goals, and personal projects with full privacy.",
    icon: "🏠",
    category: "Personal",
    color: "from-violet-500/20 to-fuchsia-500/10",
    accentColor: "#8B5CF6",
    tags: ["personal", "private"],
  },
  {
    id: "open-source",
    name: "Open Source",
    description: "Community contributions, issue tracking, and release management.",
    icon: "🌐",
    category: "Open Source",
    color: "from-lime-500/20 to-green-500/10",
    accentColor: "#84CC16",
    tags: ["opensource", "community"],
  },
];
